In [2]:
# IMPORTING IMPORTANT LIBRARIES

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder ,StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns

# IMPRTING DATASETS

In [3]:
data=pd.read_csv('winequality-red.csv')

In [5]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [6]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [8]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [36]:
#Making binary classificaion for the response variable.
#Dividing wine as good and bad by giving the limit for the quality
bins = (2, 6.5, 8)
group_names = ['bad', 'good']
data['quality'] = pd.cut(data['quality'], bins = bins, labels = group_names)

In [37]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol quality  
0         9.4     bad  
1         9.8     bad  
2         9.8     bad  
3         9.8     bad  
4         9.4     bad  
...       ...     ...  
1594     10.5     bad  
1595     11.2     bad  
1596     11.0     bad  
1597     10.2     bad  
1598     11.0     bad  

[1599 rows x 12 columns]

# SPLITTING DATA INTO TARGET AND FEATURES

In [38]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [39]:
# train test  split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=7)

In [40]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1279, 11)
(320, 11)
(1279,)
(320,)


In [41]:
# LABEL ENCODER
LE=LabelEncoder()
LE.fit(y_train)
y_train_enc=LE.transform(y_train)
LE.fit(y_test)
y_test_enc=LE.transform(y_test)


In [42]:
y_train_enc

array([0, 0, 0, ..., 0, 0, 0])

# Model building and prediction

In [43]:
model=LogisticRegression(solver='liblinear')
model.fit(X_train,y_train_enc)
y_pred=model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score, recall_score , precision_score , f1_score , confusion_matrix , classification_report


ACCURACY=accuracy_score(y_test_enc,y_pred)
RECALL=recall_score(y_test_enc,y_pred)
PRECISION=precision_score(y_test_enc,y_pred)
F1=f1_score(y_test_enc,y_pred)
C_M=confusion_matrix(y_test_enc,y_pred)
C_R=classification_report(y_test_enc,y_pred)



In [45]:
print(ACCURACY)
print(RECALL)
print(F1)
print(PRECISION)
print(C_R)
print(C_M)

0.871875
0.36585365853658536
0.4225352112676056
0.5
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       279
           1       0.50      0.37      0.42        41

    accuracy                           0.87       320
   macro avg       0.71      0.66      0.68       320
weighted avg       0.86      0.87      0.86       320

[[264  15]
 [ 26  15]]


In [46]:
model_1=RandomForestClassifier()
model_1.fit(X_train,y_train_enc)
y_pred_1=model_1.predict(X_test)

In [47]:
ACCURACY_1=accuracy_score(y_test_enc,y_pred_1)
RECALL_1=recall_score(y_test_enc,y_pred_1)
PRECISION_1=precision_score(y_test_enc,y_pred_1)
F1_1=f1_score(y_test_enc,y_pred_1)
C_M_1=confusion_matrix(y_test_enc,y_pred_1)
C_R_1=classification_report(y_test_enc,y_pred_1)



In [48]:
print(ACCURACY_1)
print(RECALL_1)
print(F1_1)
print(PRECISION_1)
print(C_R_1)
print(C_M_1)

0.896875
0.5853658536585366
0.5925925925925926
0.6
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       279
           1       0.60      0.59      0.59        41

    accuracy                           0.90       320
   macro avg       0.77      0.76      0.77       320
weighted avg       0.90      0.90      0.90       320

[[263  16]
 [ 17  24]]
